spring:
  cloud:
    gateway:
      routes:
        - id: medicamento
          uri: lb://APPPBAPIMEDICAMENTO
          filters:
            - StripPrefix=1
          predicates:
            - Path=/medicamento/**
        - id: paciente
          uri: lb://APPPBAPIPACIENTE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/paciente/**
        - id: receitamedica
          uri: lb://APPPBAPIRECEITAMEDICA
          filters:
            - StripPrefix=1
          predicates:
            - Path=/receita/**
  application:
    name: Gateway
server:
  port: 9000
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/